"""initial database

Revision ID: cd65a58f0ddf
Revises: 
Create Date: 2026-07-15 10:22:55.314608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd65a58f0ddf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False, comment='城市名称'),
    sa.Column('province', sa.String(length=50), nullable=False, comment='省份'),
    sa.Column('country', sa.String(length=50), nullable=False, comment='国家'),
    sa.Column('description', sa.Text(), nullable=True, comment='城市描述'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图URL'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='城市等级: 热门/普通/小众'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='用户自己的大模型API Key'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='收藏目标类型: scenic_spot/hotel/restaurant'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='收藏目标ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('city_id', sa.BigInteger(), nullable=False, comment='所属城市ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='酒店名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='酒店描述'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分'),
    sa.Column('open_time', sa.String(length=100), nullable=True, comment='开业时间'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='图片URL'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurants',
    sa.Column('city_id', sa.BigInteger(), nullable=False, comment='所属城市ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='餐厅名称'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='菜系类别'),
    sa.Column('description', sa.Text(), nullable=True, comment='餐厅描述'),
    sa.Column('price_level', sa.String(length=20), nullable=True, comment='价格水平'),
    sa.Column('score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='图片URL'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='评论目标类型: scenic_spot/hotel/restaurant'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='评论目标ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenic_spots',
    sa.Column('city_id', sa.BigInteger(), nullable=False, comment='所属城市ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='景点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='景点描述'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='景点类别'),
    sa.Column('score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='评分'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='门票价格'),
    sa.Column('open_time', sa.String(length=100), nullable=True, comment='开放时间'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='图片URL'),
    sa.Column('tags_json', sa.JSON(), nullable=True, comment='标签JSON, 用于AI推荐'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_plans',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='计划标题'),
    sa.Column('destination', sa.String(length=100), nullable=False, comment='目的地'),
    sa.Column('days', sa.Integer(), nullable=False, comment='旅行天数'),
    sa.Column('budget', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='预算'),
    sa.Column('plan_json', sa.JSON(), nullable=True, comment='结构化行程JSON'),
    sa.Column('markdown', sa.Text(), nullable=True, comment='AI生成的可展示Markdown文本'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('preference_type', sa.String(length=50), nullable=False, comment='偏好类型'),
    sa.Column('preference_value', sa.String(length=255), nullable=False, comment='偏好值'),
    sa.Column('weight', sa.Float(), nullable=False, comment='权重'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('travel_plans')
    op.drop_table('scenic_spots')
    op.drop_table('reviews')
    op.drop_table('restaurants')
    op.drop_table('hotels')
    op.drop_table('favorites')
    op.drop_table('ai_sessions')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
